linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
#    - err113
    - errchkjson
    - errname
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - iface
    - intrange
    - ireturn
    - makezero
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - perfsprint
    - prealloc
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
#    - wrapcheck
    - wsl
