name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Verify dependencies
        run: go mod verify

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true

      - name: Run unit testing
        run: make test

  build:
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build
