name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Tidy
        run: go mod tidy

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true
